### ISSUE TITLE
Tests failing on Travis and CRAN:

### ISSUE THREAD

**Issue by petermeissner** [petermeissner/statsgrokse#3]
Tests failing on Travis and CRAN:

Travis: https://travis-ci.org/petermeissner/statsgrokse
CRAN: https://cran.r-project.org/web/checks/check_results_statsgrokse.html

... this seems to be due to the server being taken down. (see also https://github.com/petermeissner/wikipediatrend/issues/31)

**Comment by projectflutrend** [comment]
Do you know if this will be permanent?

**Comment by petermeissner** [comment]
No, I do not know but I suspect it is.
